### PR TITLE
Cache changes

### PR DESCRIPTION
**Pull request by jeremeguenther**
1. added feature to auto gen entity tracking implementation code.
2. added cache methods for indexes, foreign keys, getall, and custom
sprocs.
3. Added option to upgrade caching code to System.Runtime.

-- The naming convention for the new methods are: GetCacheBy<IndexName>; an alternate name contemplated was CacheBy<IndexName>.

### CODE REVIEW

**Comment by jeremeguenther** [comment]
I am questioning whether the Cache methods should simply be overloads on their Get methods.  By the time I was done with them they did seem to belong there more.

**Comment by niemyjski** [comment]
Yeah, I'd just create extension methods where possible and keep the interface small as possible. Have you tested these changes with different versions of ent lib selected to make sure it generates?

**Comment by jeremeguenther** [comment]
No, I only tested with Ent Lib 5.  The EnterpriseLibrary caching code has existed in NetTiers for quite some time, I left all that alone for the most part.  The big change was the upgrade to System.Runtime.

I will change the methods to overloads and re-submit the code.

**Comment by jeremeguenther** [comment]
I have changed the method names

**Comment by niemyjski** [comment]
Thanks for the updates. Would you mind quickly generating against the different dot net versions and ent lib versions, we just need to make sure it compiles as long as you did testing on enterprise lib 5 branch. Then we can merge it in.

by doing so will tell us real quick if anything was broken :)

**Comment by jeremeguenther** [comment]
Tested combinations for generation and building:
DotNet v4_5 EntLib v5_0 CacheLayer None (Success)
DotNet v4_5 EntLib v5_0 CacheLayer EntLib (Success)
DotNet v4_5 EntLib v5_0 CacheLayer SysRun (Success)
DotNet v3_5 EntLib v3_1 CacheLayer EntLib (Success)
DotNet v3_5 EntLib v3_1 CacheLayer None (Success)
DotNet v3_5 EntLib v3_1 CacheLayer SysRun (Successful generate, Failure build - runtime didn't exist in this version of .net)
DotNet v2 EntLib v3_1 CacheLayer None (Success)
DotNet v2 EntLib v3_1 CacheLayer EntLib (Success)

**Comment by niemyjski** [comment]
Sounds good :) When you said runtime didn't exist you mean like your .net runtime or ? mine sending me a the stack trace if you still have it? Is it something I need to take a look into?

**Comment by jeremeguenther** [comment]
I don't have it anymore.  I could regenerate if you really needed it.

What I was trying to impart is that the System.Runtime.Cache did not exist prior to version 4 of .NET.  That is why the Enterprise Library was originally used for the Caching layer.  Microsoft did away with that library for version 4 of .NET which is why I added the upgrade option converting it to the System.Runtime namespace.

So if you try and select the SysRun Cache option when generating for versions of .net older than 4 the resulting code will not compile.

**Comment by niemyjski** [comment]
Gotcha, do you think we should add a check to blow up with a friendly error message if you selected it and are not on 4.0?

**Comment by jeremeguenther** [comment]
It would be nice if CodeSmith could have dependencies built in so certain variable values were disallowed based on another variables choice.  However, I did not see that option.

Short of that, I figure it can be figured out by the user.  Similar to someone making the mistake of choosing .net v2 and Enterprise Library v5.

**Comment by niemyjski** [comment]
Fair enough :) Thanks for your contribution!

**Pull request merged**
